# Generated by Django 4.0.2 on 2022-02-27 11:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('degisnation', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=api.models.upload_client_say_image)),
            ],
        ),
    ]
