# Generated by Django 4.0.2 on 2022-02-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsay',
            name='degisnation',
            field=models.TextField(max_length=300),
        ),
    ]
