# Generated by Django 4.0.2 on 2022-02-27 11:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clientsay_degisnation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('degisnation', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to=api.models.upload_about_us_image)),
            ],
        ),
    ]
