# Generated by Django 4.0.2 on 2022-02-26 19:56

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=service.models.upload_category_image)),
            ],
            options={
                'verbose_name_plural': 'Category List',
            },
        ),
    ]
